server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: transaction-route
          uri: lb://transaction-management
          predicates:
            - Path=/api/transaction/**
        - id: wallet-management-view-route
          uri: lb://wallet-management-view
          predicates:
            - Path=/api/wallet/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"
