server:
  port: 0

spring:
  application:
    name: transaction-management
  datasource:
    url: jdbc:postgresql://localhost:5432/event-store
    username: ${psql.username}
    password: ${psql.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
  config:
    import: classpath:hidden.yml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"
