server:
  port: 0

app:
  default-wallet-id: 467f7419-e9ac-4ffd-8a02-7e11310b0de0

spring:
  application:
    name: wallet-management-view
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet-view
    username: ${psql.username}
    password: ${psql.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
  liquibase:
    enabled: false
  config:
    import: classpath:hidden.yml

axon:
  axonserver:
    servers: localhost:8124
  eventhandling:
    processors:
      wallet-processor:
        mode: tracking

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"
