server:
  port: 0

app:
  default-wallet-id: 467f7419-e9ac-4ffd-8a02-7e11310b0de0
  initial-date: 2019-10-05T13:00:00+00:00
  initial-balance: 1000

spring:
  application:
    name: wallet-management
  datasource:
    url: jdbc:postgresql://localhost:5432/event-store
    username: ${psql.username}
    password: ${psql.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
  config:
    import: classpath:hidden.yml

axon:
  eventhandling:
    processors:
      transaction-processor:
        mode: tracking

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"
